development:
  dialect: "sqlite3"
  database: /data/sqlite_data/dasecho_development.sqlite

test:
  dialect: "sqlite3"
  database: /data/sqlite_data/dasecho_development.sqlite

production:
  dialect: "sqlite3"
  database: /data/sqlite_data/dasecho_development.sqlite

