development:
  dialect: "sqlite3"
  database: /data/www/dasecho.net/dasecho_development.sqlite

test:
  dialect: "sqlite3"
  database: /data/www/dasecho.net/dasecho_development.sqlite

production:
  dialect: "sqlite3"
  database: /data/www/dasecho.net/dasecho_development.sqlite

